### ISSUE TITLE
OCR --> S3 --> OPF

### ISSUE THREAD

**Issue by ngawangtrinley** [OpenPecha/openpecha-toolkit#39]
OCR --> S3 : json.gzip + images
OCR --> opf: base text + page layer
OCR --> opf release: boundingPoly zipped

**Comment by ngawangtrinley** [comment]
@eroux we won't do S3 to opf because it would mean we'd have to download the huge files somewhere, unzip them and extract the data. It'll be easy enough to do that later when needed. We'll however include the sentence bounding boxes coordinates in the first release of every OCRed opf.

![image](https://user-images.githubusercontent.com/17675331/73330362-895a9300-429b-11ea-9081-a0a507587d28.png)

**Comment by eroux** [comment]
ah nice! Once you have a good workflow I'll also make a script to import that into BUDA so that we can make a nice demo
